tr = ['veya', 'en', 'gün', 'bu', 'tutmak', 'para', 'ilk', 'üzerine', 'büyük', 'biraz', 'girmek', 'yani', 'için', 'ön', 'bütün', 'doğru', 'çünkü', 
've', 'hiç', 'dönmek', 'ara', 'bunun', 'anlatmak', 'sevmek', 'taraf', 'söz', 'sistem', 'oturmak', 'küçük', 'ev', 'önemli', 'bunlar', 'ya',
'düşünmek', 'kendi', 'bir', 'bile', 'saat', 'gitmek', 'tüm', 'şimdi', 'diğer', 'gibi', 'kitap', 'getirmek', 'ürün', 'fazla', 'ki', 'orta',
'yer', 'iyi', 'süre', 'dış', 'yaş', 'burada', 'adam', 'insan', 'güzel', 'hiçbir', 'çıkarmak', 'zaman', 'anne', 'ise', 'şu', 'alan', 'nasıl',
'şey', 'beklemek', 'hem', 'kadar', 'sorun', 'birbiri', 'duymak', 'zor', 'baba', 'vermek', 'şekil', 'kadın', 'arkadaş', 'hal', 'sen', 'iki', 
'ama', 'bulmak', 'an', 'çocuk', 'etmek', 'ne', 'ay', 'kalmak', 'uzun', 'olmak', 'istemek', 'açmak', 'artık', 'çıkmak', 'alınmak', 'kapı', 
'sormak', 'su', 'bunu', 'az', 'birlikte', 'ben', 'yıl', 'bakmak', 'göz', 'durum', 'aynı', 'almak', 'ses', 'yapılmak', 'bırakmak', 'konu', 
'gelmek', 'var', 'öyle', 'iç', 'bugün', 'onlar', 'siz', 'yapmak', 'el', 'söylemek', 'diye', 'gerekmek', 'çok', 'biri', 'yine', 'verilmek', 
'yaşamak', 'genç', 'bazı', 'çekmek', 'bilmek', 'yemek', 'yol', 'son', 'düşmek', 'dünya', 'konuşmak', 'yüzde', 'sağlamak', 'neden', 'tek', 
'demek', 'durmak', 'içinde', 'yüz', 'baş', 'önce', 'yan', 'koymak', 'dönem', 'hep', 'kız', 'ile', 'ancak', 'alt', 'olay', 'karşı', 'daha', 
'yazmak', 'ülke', 'atmak', 'çalışmak', 'anlamak', 'göre', 'kişi', 'üzerinde', 'gece', 'sadece', 'bilgi', 'ad', 'biz', 'sahip', 'bulunmak', 
'başka', 'sonra', 'işte', 'hayat', 'iş', 'yok', 'her', 'yeni', 'görmek', 'onun', 'değil', 'kim', 'böyle', 'sıra', 'geçmek', 'başlamak', 
'devlet', 'hemen', 'sonuç']

en = ['group', 'life', 'see', 'last', 'across', 'think', 'able', 'music', 'small', 'second', 'seek', 'have', 'serve', 'cover', 'case', 'about',
'family', 'apply', 'grow', 'hand', 'make', 'leave', 'at', 'above', 'a', 'without', 'adjectives', 'he', 'long', 'tell', 'others', 'they', 
'other', 'same', 'do', 'answer', 'verbs', 'you', 'right', 'first', 'her', 'thing', 'bad', 'check', 'own', 'know', 'big', 'as',
'it', 'player', 'say', 'week', 'surface', 'hair', 'problem', 'large', 'by', 'little', 'toward', 'game', 'animal', 'try', 'the', 'point', 
'ask', 'loss', 'number', 'few', 'with', 'high', 'soldier', 'and', 'way', 'industry', 'cause', 'control', 'new', 'over', 'far', 'cell', 
'eye', 'tough', 'use', 'man', 'of', 'exist', 'after', 'part', 'i', 'want', 'not', 'language', 'cut', 'white','effort', 'kitchen','vote',
'where', 'but', 'word', 'into', 'employee', 'senior', 'that', 'ever', 'be', 'to', 'from', 'come', 'nation', 'water', 'for', 'treat',
'company', 'take', 'his', 'dark', 'person', 'go', 'an', 'resource', 'year', 'find', 'foreign', 'worker', 'feel', 'get', 'on', 'tree', 'item', 
'stock', 'wait', 'young', 'image', 'friend', 'world', 'beyond', 'work', 'this', 'ten', 'old', 'seem', 'child', 'fact', 'lose', 'time', 'give', 
'rock', 'start', 'nearly', 'woman', 'practice', 'in', 'every', 'measure', 'decide', 'yeah', 'lay', 'talk', 'kid', 'great', 'or', 'early', 'nice',
'himself', 'she', 'focus', 'away', 'look', 'public', 'up', 'stay', 'black', 'shoulder','place', 'day', 'common', 'next', 'call', 'good', ]